### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by PikyCZ** [PikyCZ/PictureLogin#1]
- [x] com.bobacadodl.imgmessage - ImageChar
- [x] com.bobacadodl.commands - BaseCommand
- [x] com.bobacadodl.config - ConfigManager 
- [ ] com.bobacadodl.Listeners - Join a Quit Listener

**Comment by PikyCZ** [comment]
listeners is fixed.. now i need help with imagechar class :O

**Comment by XDqrkneZ** [comment]
doesn't work

**Comment by XDqrkneZ** [comment]
the pokkit and the spigot plugin i mean

**Comment by XDqrkneZ** [comment]
did  you stop
